# Copyright 2026 Canonical Ltd.
# See LICENSE file for licensing details.

name: Integration tests

on:
  pull_request:
  schedule:
    - cron: "0 15 * * SAT"
  workflow_dispatch:

concurrency:
  group: integration-test-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build charm
    uses: ./.github/workflows/build.yaml
    secrets: inherit

  integration-tests:
    name: Integration tests
    needs: build
    runs-on: ubuntu-latest
    timeout-minutes: 120
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Download charm artifact
        uses: actions/download-artifact@v4
        with:
          pattern: ${{ needs.build.outputs.artifact-prefix }}-*--platform-ubuntu@24.04-amd64
          merge-multiple: true

      - name: Set up LXD and Juju
        uses: charmed-kubernetes/actions-operator@main
        with:
          provider: lxd
          juju-channel: 3/stable

      - name: Install uv
        uses: astral-sh/setup-uv@v7

      - name: Run integration tests
        run: uv run --group integration pytest -v --tb native tests/integration
